### ISSUE TITLE
This shit doesn't fucking work.

### ISSUE THREAD

**Issue by arizvisa** [raelldottin/AutogenRestApiEndpoints#1]
How do I build it?

**Comment by raelldottin** [comment]
The project has yet to start. I'm sorry. I'm not amazing like Poison_Metal. 🤣

**Comment by arizvisa** [comment]
lol. wow, there's a name i haven't heard in a lifetime. whatever happened to that fuqer? there was another kid that we knew, i forgot his nick but his name was mickey (michael) spears or something.

**Comment by raelldottin** [comment]
No clue. After BOA and his crew popped the IRC server, they all went on with their lives. It will take some effort to remember folks' handles from back then.

**Comment by raelldottin** [comment]
@arizvisa if you got $20k worth of bug bounties. pls, send them my way. i need cash for a telsa. thnx
